clouds:
  osp_admin:                                 # Name of this cloud
    auth:
      auth_url: https://cscloud.lnu.se:5000 # API endpoint
      project_name: admin                    # OpenStack Project name
      username: tk222vz-4me307                        # Authentication user
      password: 'AdminPssword'             # User password
    identity_api_version: 3
    region_name: RegionOne                   # OpenStack region
    operation_log:                           # Client Logging configurations
      logging: TRUE
      file: ~/openstackclient_admin.log
      level: info
