image: node:16

.before_script_ssh: &before_script_ssh
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' > ~/.ssh/id_rsa
    - echo "${SSH_PUBLIC_KEY}" | tr -d '\r' > ~/.ssh/id_rsa.pub
    - chmod 600 ~/.ssh/id_rsa
    - chmod 644 ~/.ssh/id_rsa.pub
    - cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys
    - ssh-keyscan gitlab.lnu.se >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-keygen -f ~/.ssh/id_rsa -p
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'



deploy-client-job:
  extends: .before_script_ssh
  stage: deploy
  script:
    - cd /builds/tk222vz/ia-pipeline/clientside/
    - chmod +x deploy.sh
    - bash deploy.sh

